# Generated by Django 3.2.16 on 2023-06-11 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='recipes/')),
                ('cooking_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL, verbose_name='Recipe author')),
                ('tags', models.ManyToManyField(related_name='Tags', to='recipes.Tag', verbose_name='Recipe')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
