# Generated by Django 3.2.16 on 2023-06-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribed',
            options={'ordering': ('-id',), 'verbose_name': 'Моя подписка', 'verbose_name_plural': 'Мои подписки'},
        ),
    ]
