# Generated by Django 3.2.16 on 2023-06-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_subscribed_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribed',
            options={'ordering': ('-id',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Мои подписки'},
        ),
    ]
