# Generated by Django 3.2.16 on 2023-06-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subscribed_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribed',
            new_name='Subscriber',
        ),
    ]
